# Generated by Django 2.2.7 on 2019-11-20 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_fname', models.CharField(help_text='enter the firstname', max_length=200)),
                ('c_lname', models.CharField(help_text='enter the lname', max_length=200)),
                ('c_address', models.CharField(help_text='enter the address', max_length=200)),
                ('c_pno', models.IntegerField(help_text='enter the phone number')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(help_text='enter the name of hotel', max_length=100)),
                ('hotel_city', models.CharField(help_text='enter the city', max_length=200)),
                ('hotel_state', models.CharField(max_length=100)),
                ('hotel_pno', models.IntegerField(help_text='enter the phone number')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(help_text='enter the type of room', max_length=200)),
                ('room_rate', models.IntegerField(help_text='enter the room rate')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField(max_length=200)),
                ('checkout_date', models.DateField(max_length=200)),
                ('room_status', models.CharField(help_text='enter the status', max_length=200)),
                ('noof_guest', models.IntegerField(help_text='enter the no of guests')),
                ('reserve_date', models.DateField(max_length=200)),
                ('c_fname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_chrage', models.IntegerField(help_text='enter the room charge')),
                ('maintaince_charge', models.IntegerField(help_text='enter the maintance charge')),
                ('payment_date', models.DateField(max_length=200)),
                ('c_fname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.Customer')),
            ],
        ),
    ]
