# Generated by Django 2.2.7 on 2019-11-20 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0002_auto_20191120_0913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reserve_date',
            new_name='reservation_date',
        ),
    ]
