# Generated by Django 2.2.7 on 2019-11-20 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0003_auto_20191120_0920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='c_fname',
            new_name='customer_fname',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='c_fname',
            new_name='customer_fname',
        ),
    ]
